export { Header } from "./Header";
export { HeroSection } from "./HeroSection";
export { MetricsSection } from "./MetricsSection";
export { ProblemSolvingSection } from "./ProblemSolvingSection";
export { ApproachesSection } from "./ApproachesSection";
export { DevelopmentApproachSection } from "./DevelopmentApproachSection";
export { TechStackSection } from "./TechStackSection";
export { Footer } from "./Footer";

// 기존 상세 섹션들 (필요시 사용)
export { DomainExpertiseSection } from "./DomainExpertiseSection";
export { ArchitectureSection } from "./ArchitectureSection";
export { TypeScriptSection } from "./TypeScriptSection";
export { TanStackQuerySection } from "./TanStackQuerySection";
export { I18nSection } from "./I18nSection";
export { AdminStructureSection } from "./AdminStructureSection";
export { StickyHeaderSection } from "./StickyHeaderSection";
export { DataTableSection } from "./DataTableSection";
export { DynamicFormSection } from "./DynamicFormSection";
export { InvoiceSection } from "./InvoiceSection";
export { UnitTestSection } from "./UnitTestSection";
export { ClaudeCodeSection } from "./ClaudeCodeSection";
export { CICDSection } from "./CICDSection";
export { SmsEmailSection } from "./SmsEmailSection";
